name: Google Internal Tests Enforcement

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: read
  statuses: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: angular/dev-infra/github-actions/google-internal-tests@658ea9ec012d34882807f0be093812961af79cce
        with:
          run-tests-guide-url: http://go/angular/g3sync
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sync-config: ./.ng-dev/g3-sync-config.json
